### ISSUE TITLE
It looks like bundler-as_of does not work with more recent versions of Bundler?

### ISSUE THREAD

**Issue by davidstosik** [flavorjones/bundler-as_of#9]
After a conversation started by @Schwad, I tried using bundler-as_of to force a given Rails version to install as it would have on its day of release. 

<details><summary>This contains my preliminary findings trying to do this with Rails.</summary>

Following the steps below seemed to work, until I got an error.

```
# in any directory that does not have a Gemfile
bundle plugin install bundler-as_of # check ~/.bundle/plugin/gems for the plugin
gem install rails --version "7.0.3"

BUNDLE_AS_OF=2022-05-10 rails _7.0.3_ new --minimal rails703_test
      create
      create  README.md
      create  Rakefile
      create  .ruby-version
      create  config.ru
      create  .gitignore
      create  .gitattributes
      create  Gemfile
         run  git init from "."
Initialized empty Git repository in /Users/sto/src/test_versions/rails703_test/.git/
      create  app
      create  app/assets/config/manifest.js
      create  app/assets/stylesheets/application.css
      create  app/channels/application_cable/channel.rb
      create  app/channels/application_cable/connection.rb
      create  app/controllers/application_controller.rb
      create  app/helpers/application_helper.rb
      create  app/jobs/application_job.rb
      create  app/mailers/application_mailer.rb
      create  app/models/application_record.rb
      create  app/views/layouts/application.html.erb
      create  app/views/layouts/mailer.html.erb
      create  app/views/layouts/mailer.text.erb
      create  app/assets/images
      create  app/assets/images/.keep
      create  app/controllers/concerns/.keep
      create  app/models/concerns/.keep
      create  bin
      create  bin/rails
      create  bin/rake
      create  bin/setup
      create  config
      create  config/routes.rb
      create  config/application.rb
      create  config/environment.rb
      create  config/puma.rb
      create  config/environments
      create  config/environments/development.rb
      create  config/environments/production.rb
      create  config/environments/test.rb
      create  config/initializers
      create  config/initializers/assets.rb
      create  config/initializers/content_security_policy.rb
      create  config/initializers/cors.rb
      create  config/initializers/filter_parameter_logging.rb
      create  config/initializers/inflections.rb
      create  config/initializers/new_framework_defaults_7_0.rb
      create  config/initializers/permissions_policy.rb
      create  config/locales
      create  config/locales/en.yml
      create  config/master.key
      append  .gitignore
      create  config/boot.rb
      create  config/database.yml
      create  db
      create  db/seeds.rb
      create  lib
      create  lib/tasks
      create  lib/tasks/.keep
      create  lib/assets
      create  lib/assets/.keep
      create  log
      create  log/.keep
      create  public
      create  public/404.html
      create  public/422.html
      create  public/500.html
      create  public/apple-touch-icon-precomposed.png
      create  public/apple-touch-icon.png
      create  public/favicon.ico
      create  public/robots.txt
      create  tmp
      create  tmp/.keep
      create  tmp/pids
      create  tmp/pids/.keep
      create  tmp/cache
      create  tmp/cache/assets
      create  vendor
      create  vendor/.keep
      create  test/fixtures/files
      create  test/fixtures/files/.keep
      create  test/controllers
      create  test/controllers/.keep
      create  test/mailers
      create  test/mailers/.keep
      create  test/models
      create  test/models/.keep
      create  test/helpers
      create  test/helpers/.keep
      create  test/integration
      create  test/integration/.keep
      create  test/channels/application_cable/connection_test.rb
      create  test/test_helper.rb
      remove  app/jobs
      remove  app/views/layouts/mailer.html.erb
      remove  app/views/layouts/mailer.text.erb
      remove  app/mailers
      remove  test/mailers
      remove  app/javascript/channels
      remove  app/channels
      remove  test/channels
      remove  config/initializers/cors.rb
      remove  config/initializers/new_framework_defaults_7_0.rb
         run  bundle install
NOTE: bundler-as_of: bundling dependencies as of 2022-05-10 ...
NOTE: bundler-as_of: resolving rails ["~> 7.0.3"] to 7.0.3 released on 2022-05-09
NOTE: bundler-as_of: resolving sprockets-rails [">= 0"] to 3.4.2 released on 2021-12-11
NOTE: bundler-as_of: resolving sqlite3 ["~> 1.4"] to 1.4.2 released on 2019-12-18
NOTE: bundler-as_of: resolving puma ["~> 5.0"] to 5.6.4 released on 2022-03-30
NOTE: bundler-as_of: resolving tzinfo-data [">= 0"] to 1.2022.1 released on 2022-03-17
NOTE: bundler-as_of: resolving debug [">= 0"] to 1.5.0 released on 2022-03-30
ERROR: please remove bundler from the Gemfile or gemspec
/Users/sto/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/friendly_errors.rb:59:in `exit_status': undefined method `status_code' for #<Bundler::BundlerError: ERROR: please remove bundler from the Gemfile or gemspec> (NoMethodError)

      when BundlerError then error.status_code
                                  ^^^^^^^^^^^^
        from /Users/sto/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/friendly_errors.rb:127:in `rescue in with_friendly_errors'
        from /Users/sto/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/friendly_errors.rb:118:in `with_friendly_errors'
        from /Users/sto/.gem/ruby/3.1.2/gems/bundler-2.3.22/exe/bundle:36:in `<main>'
/Users/sto/.bundle/plugin/gems/bundler-as_of-0.1.0/lib/bundler/as_of.rb:41:in `block in resolve_transitive_dependencies': ERROR: please remove bundler from the Gemfile or gemspec (Bundler::BundlerError)
        from /Users/sto/.bundle/plugin/gems/bundler-as_of-0.1.0/lib/bundler/as_of.rb:39:in `each'
        from /Users/sto/.bundle/plugin/gems/bundler-as_of-0.1.0/lib/bundler/as_of.rb:39:in `resolve_transitive_dependencies'
        from /Users/sto/.bundle/plugin/gems/bundler-as_of-0.1.0/lib/bundler/as_of.rb:24:in `modify_dependencies'
        from /Users/sto/.bundle/plugin/gems/bundler-as_of-0.1.0/lib/bundler/as_of.rb:140:in `block in <top (required)>'
        from /Users/sto/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/plugin.rb:232:in `block in hook'
        from /Users/sto/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/plugin.rb:232:in `each'
        from /Users/sto/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/plugin.rb:232:in `hook'
        from /Users/sto/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/installer.rb:22:in `install'
        from /Users/sto/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/cli/install.rb:62:in `run'
        from /Users/sto/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/cli.rb:257:in `block in install'
        from /Users/sto/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/settings.rb:131:in `temporary'
        from /Users/sto/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/cli.rb:256:in `install'
        from /Users/sto/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /Users/sto/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /Users/sto/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        from /Users/sto/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/cli.rb:31:in `dispatch'
        from /Users/sto/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        from /Users/sto/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/cli.rb:25:in `start'
        from /Users/sto/.gem/ruby/3.1.2/gems/bundler-2.3.22/exe/bundle:48:in `block in <main>'
        from /Users/sto/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/friendly_errors.rb:120:in `with_friendly_errors'
        from /Users/sto/.gem/ruby/3.1.2/gems/bundler-2.3.22/exe/bundle:36:in `<main>'
         run  bundle binstubs bundler
Resolving dependencies...
```

It seems to have failed creating a `Gemfile.lock`, so I tried
```
cd rails703_test
BUNDLE_AS_OF=2022-05-10 bundle
```

And it turns out it fails again with a similar error:
```
BUNDLE_AS_OF=2022-05-10 bundle
NOTE: bundler-as_of: bundling dependencies as of 2022-05-10 ...
NOTE: bundler-as_of: resolving rails ["~> 7.0.3"] to 7.0.3 released on 2022-05-09
NOTE: bundler-as_of: resolving sprockets-rails [">= 0"] to 3.4.2 released on 2021-12-11
NOTE: bundler-as_of: resolving sqlite3 ["~> 1.4"] to 1.4.2 released on 2019-12-18
NOTE: bundler-as_of: resolving puma ["~> 5.0"] to 5.6.4 released on 2022-03-30
NOTE: bundler-as_of: resolving tzinfo-data [">= 0"] to 1.2022.1 released on 2022-03-17
NOTE: bundler-as_of: resolving debug [">= 0"] to 1.5.0 released on 2022-03-30
ERROR: please remove bundler from the Gemfile or gemspec
/Users/sto/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/friendly_errors.rb:59:in `exit_status': undefined method `status_code' for #<Bundler::BundlerError: ERROR: please remove bundler from the Gemfile or gemspec> (NoMethodError)

      when BundlerError then error.status_code
                                  ^^^^^^^^^^^^
        from /Users/sto/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/friendly_errors.rb:127:in `rescue in with_friendly_errors'
        from /Users/sto/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/friendly_errors.rb:118:in `with_friendly_errors'
        from /Users/sto/.gem/ruby/3.1.2/gems/bundler-2.3.22/exe/bundle:36:in `<top (required)>'
        from /Users/sto/.gem/ruby/3.1.2/bin/bundle:25:in `load'
        from /Users/sto/.gem/ruby/3.1.2/bin/bundle:25:in `<main>'
/Users/sto/.bundle/plugin/gems/bundler-as_of-0.1.0/lib/bundler/as_of.rb:41:in `block in resolve_transitive_dependencies': ERROR: please remove bundler from the Gemfile or gemspec (Bundler::BundlerError)
        from /Users/sto/.bundle/plugin/gems/bundler-as_of-0.1.0/lib/bundler/as_of.rb:39:in `each'
        from /Users/sto/.bundle/plugin/gems/bundler-as_of-0.1.0/lib/bundler/as_of.rb:39:in `resolve_transitive_dependencies'
        from /Users/sto/.bundle/plugin/gems/bundler-as_of-0.1.0/lib/bundler/as_of.rb:24:in `modify_dependencies'
        from /Users/sto/.bundle/plugin/gems/bundler-as_of-0.1.0/lib/bundler/as_of.rb:140:in `block in <top (required)>'
        from /Users/sto/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/plugin.rb:232:in `block in hook'
        from /Users/sto/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/plugin.rb:232:in `each'
        from /Users/sto/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/plugin.rb:232:in `hook'
        from /Users/sto/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/installer.rb:22:in `install'
        from /Users/sto/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/cli/install.rb:62:in `run'
        from /Users/sto/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/cli.rb:257:in `block in install'
        from /Users/sto/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/settings.rb:131:in `temporary'
        from /Users/sto/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/cli.rb:256:in `install'
        from /Users/sto/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /Users/sto/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /Users/sto/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        from /Users/sto/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/cli.rb:31:in `dispatch'
        from /Users/sto/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        from /Users/sto/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/cli.rb:25:in `start'
        from /Users/sto/.gem/ruby/3.1.2/gems/bundler-2.3.22/exe/bundle:48:in `block in <top (required)>'
        from /Users/sto/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/friendly_errors.rb:120:in `with_friendly_errors'
        from /Users/sto/.gem/ruby/3.1.2/gems/bundler-2.3.22/exe/bundle:36:in `<top (required)>'
        from /Users/sto/.gem/ruby/3.1.2/bin/bundle:25:in `load'
        from /Users/sto/.gem/ruby/3.1.2/bin/bundle:25:in `<main>'
```

</details>

It turns out, however, that I have a simpler way to reproduce:

```
mkdir testapp && cd testapp
bundle init
echo 'gem "rails"' >> Gemfile
bundle plugin install bundler-as_of
BUNDLE_AS_OF=2022-05-10 bundle install
```

This generates the same errors:

```
NOTE: bundler-as_of: bundling dependencies as of 2022-05-10 ...
NOTE: bundler-as_of: resolving rails [">= 0"] to 7.0.3 released on 2022-05-09
ERROR: please remove bundler from the Gemfile or gemspec
/Users/sto/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/friendly_errors.rb:59:in `exit_status': undefined method `status_code' for #<Bundler::BundlerError: ERROR: please remove bundler from the Gemfile or gemspec> (NoMethodError)

      when BundlerError then error.status_code
                                  ^^^^^^^^^^^^
        from /Users/sto/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/friendly_errors.rb:127:in `rescue in with_friendly_errors'
        from /Users/sto/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/friendly_errors.rb:118:in `with_friendly_errors'
        from /Users/sto/.gem/ruby/3.1.2/gems/bundler-2.3.22/exe/bundle:36:in `<top (required)>'
        from /Users/sto/.gem/ruby/3.1.2/bin/bundle:25:in `load'
        from /Users/sto/.gem/ruby/3.1.2/bin/bundle:25:in `<main>'
/Users/sto/.bundle/plugin/gems/bundler-as_of-0.1.0/lib/bundler/as_of.rb:41:in `block in resolve_transitive_dependencies': ERROR: please remove bundler from the Gemfile or gemspec (Bundler::BundlerError)
        from /Users/sto/.bundle/plugin/gems/bundler-as_of-0.1.0/lib/bundler/as_of.rb:39:in `each'
        from /Users/sto/.bundle/plugin/gems/bundler-as_of-0.1.0/lib/bundler/as_of.rb:39:in `resolve_transitive_dependencies'
        from /Users/sto/.bundle/plugin/gems/bundler-as_of-0.1.0/lib/bundler/as_of.rb:24:in `modify_dependencies'
        from /Users/sto/.bundle/plugin/gems/bundler-as_of-0.1.0/lib/bundler/as_of.rb:140:in `block in <top (required)>'
        from /Users/sto/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/plugin.rb:232:in `block in hook'
        from /Users/sto/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/plugin.rb:232:in `each'
        from /Users/sto/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/plugin.rb:232:in `hook'
        from /Users/sto/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/installer.rb:22:in `install'
        from /Users/sto/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/cli/install.rb:62:in `run'
        from /Users/sto/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/cli.rb:257:in `block in install'
        from /Users/sto/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/settings.rb:131:in `temporary'
        from /Users/sto/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/cli.rb:256:in `install'
        from /Users/sto/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /Users/sto/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /Users/sto/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        from /Users/sto/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/cli.rb:31:in `dispatch'
        from /Users/sto/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        from /Users/sto/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/cli.rb:25:in `start'
        from /Users/sto/.gem/ruby/3.1.2/gems/bundler-2.3.22/exe/bundle:48:in `block in <top (required)>'
        from /Users/sto/.gem/ruby/3.1.2/gems/bundler-2.3.22/lib/bundler/friendly_errors.rb:120:in `with_friendly_errors'
        from /Users/sto/.gem/ruby/3.1.2/gems/bundler-2.3.22/exe/bundle:36:in `<top (required)>'
        from /Users/sto/.gem/ruby/3.1.2/bin/bundle:25:in `load'
        from /Users/sto/.gem/ruby/3.1.2/bin/bundle:25:in `<main>'
```

I'm running Bundler 2.3.22 with Ruby 3.1.2.

**Comment by Schwad** [comment]
Hey @davidstosik can confirm that I replicated this on Bundler 2.3.21 and 3.1.2 as well. Thanks for sharing this particularly with easy reproducible steps

**Comment by Schwad** [comment]
@davidstosik 

I managed to fix this bug but before throwing up a PR I realized there might be something deeper here! 😅 I `rm`'d .bundle and used a clean `plugin 'bundler-as_of', path: '~/OSS/bundler-as_of'` to use a local copy.

Firstly, when the error raises, Bundler wanted a status code to parse the error. This code is given to child classes that inherit from BundlerError.

![Screenshot 2022-10-06 at 17 36 19](https://user-images.githubusercontent.com/7865030/194369704-59f09ae1-3d08-4af8-a173-777e99753f8e.png)

SO to solve it I used one of those errors instead

![Screenshot 2022-10-06 at 17 37 39](https://user-images.githubusercontent.com/7865030/194369814-68fbd712-e008-4ea4-8f35-33ad8262d085.png)

and __voila__! no more bugs

<img width="686" alt="Screenshot 2022-10-06 at 17 38 05" src="https://user-images.githubusercontent.com/7865030/194369905-bd21e07e-9f2a-4551-8100-79394c8a438b.png">

Well, actually no, now we're just exiting gracefully with our own error.

The real problem seems to be that the `resolving` collection on your greenfield Rails app is now executing `bundler` as if it were just another gemfile dep, which we don't want. But maybe we can just ignore it? I trialed this out with `next`, and maybe we can force user's bundler to be used

![Screenshot 2022-10-06 at 17 41 56](https://user-images.githubusercontent.com/7865030/194370636-9a3778bf-3806-49a1-888b-8794b5471437.png)


Well, with this I got a *lot* farther.  In fact it seemed to resolve everything then fall over at the end. 

<img width="759" alt="Screenshot 2022-10-06 at 17 43 07" src="https://user-images.githubusercontent.com/7865030/194370887-4518c82d-7ec4-4ee3-bef0-0eda723c6db7.png">

So close! I do think we're within a small reach of solving this. Unfortunately I need to go to dinner but leaving context here for others. 

@flavorjones do you think there's a reason `bundler` is sneaking into our `resolving` nowadays? 🤔 Is it possible that my `next` approach could be enough? Happy to keep digging into this :) 

Here's my full latest error stacktrace which may help

<details>
  <summary>Full backtrace</summary>
  ```
Using railties 7.0.4
Using rails 7.0.4
Bundle complete! 45 Gemfile dependencies, 44 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.

Saving session...completed.
--- ERROR REPORT TEMPLATE -------------------------------------------------------

```
NoMethodError: undefined method `metadata' for nil:NilClass

      count = current_dependencies.count {|dep| current_specs[dep.name].first.metadata.key?("funding_uri") }
                                                             ^^^^^^^^^
  /opt/rubies/3.1.2/lib/ruby/site_ruby/3.1.0/bundler/cli/common.rb:23:in `block in output_fund_metadata_summary'
  /opt/rubies/3.1.2/lib/ruby/site_ruby/3.1.0/bundler/cli/common.rb:23:in `count'
  /opt/rubies/3.1.2/lib/ruby/site_ruby/3.1.0/bundler/cli/common.rb:23:in `output_fund_metadata_summary'
  /opt/rubies/3.1.2/lib/ruby/site_ruby/3.1.0/bundler/cli/install.rb:87:in `run'
  /opt/rubies/3.1.2/lib/ruby/site_ruby/3.1.0/bundler/cli.rb:257:in `block in install'
  /opt/rubies/3.1.2/lib/ruby/site_ruby/3.1.0/bundler/settings.rb:132:in `temporary'
  /opt/rubies/3.1.2/lib/ruby/site_ruby/3.1.0/bundler/cli.rb:256:in `install'
  /opt/rubies/3.1.2/lib/ruby/site_ruby/3.1.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /opt/rubies/3.1.2/lib/ruby/site_ruby/3.1.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /opt/rubies/3.1.2/lib/ruby/site_ruby/3.1.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /opt/rubies/3.1.2/lib/ruby/site_ruby/3.1.0/bundler/cli.rb:31:in `dispatch'
  /opt/rubies/3.1.2/lib/ruby/site_ruby/3.1.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /opt/rubies/3.1.2/lib/ruby/site_ruby/3.1.0/bundler/cli.rb:25:in `start'
  /opt/rubies/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.21/exe/bundle:48:in `block in <top (required)>'
  /opt/rubies/3.1.2/lib/ruby/site_ruby/3.1.0/bundler/friendly_errors.rb:120:in `with_friendly_errors'
  /opt/rubies/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.21/exe/bundle:36:in `<top (required)>'
  /Users/schwad/.gem/ruby/3.1.2/bin/bundle:25:in `load'
  /Users/schwad/.gem/ruby/3.1.2/bin/bundle:25:in `<main>'

```

## Environment

```
Bundler       2.3.21
  Platforms   ruby, arm64-darwin-21
Ruby          3.1.2p20 (2022-04-12 revision 4491bb740a9506d76391ac44bb2fe6e483fec952) [arm64-darwin-21]
  Full Path   /opt/rubies/3.1.2/bin/ruby
  Config Dir  /opt/rubies/3.1.2/etc
RubyGems      3.3.21
  Gem Home    /Users/schwad/.gem/ruby/3.1.2
  Gem Path    /Users/schwad/.gem/ruby/3.1.2:/opt/rubies/3.1.2/lib/ruby/gems/3.1.0
  User Home   /Users/schwad
  User Path   /Users/schwad/.gem/ruby/3.1.0
  Bin Dir     /Users/schwad/.gem/ruby/3.1.2/bin
OpenSSL       
  Compiled    OpenSSL 1.1.1n  15 Mar 2022
  Loaded      OpenSSL 1.1.1q  5 Jul 2022
  Cert File   /opt/homebrew/etc/openssl@1.1/cert.pem
  Cert Dir    /opt/homebrew/etc/openssl@1.1/certs
Tools         
  Git         2.37.3
  RVM         not installed
  rbenv       not installed
  chruby      0.3.9
```

## Bundler Build Metadata

```
Built At          2022-08-24
Git SHA           d54be5fdd8
Released Version  true
```

## Bundler settings

```
as_of
  Set via BUNDLE_AS_OF: "2022-05-10"
gem.changelog
  Set for the current user (/Users/schwad/.bundle/config): true
gem.ci
  Set for the current user (/Users/schwad/.bundle/config): "github"
gem.coc
  Set for the current user (/Users/schwad/.bundle/config): true
gem.linter
  Set for the current user (/Users/schwad/.bundle/config): "rubocop"
gem.mit
  Set for the current user (/Users/schwad/.bundle/config): true
gem.test
  Set for the current user (/Users/schwad/.bundle/config): "test-unit"
pkgs.shopify.io
  Set for the current user (/Users/schwad/.bundle/config): "token:[REDACTED]"
```

## Gemfile

### Gemfile

```ruby
# frozen_string_literal: true

source "https://rubygems.org"

plugin 'bundler-as_of', path: '~/OSS/bundler-as_of'
# gem "rails"
gem "rails"
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    actioncable (7.0.4)
      actionpack (= 7.0.4)
      activesupport (= 7.0.4)
      nio4r (~> 2.0)
      websocket-driver (>= 0.6.1)
    actionmailbox (7.0.4)
      actionpack (= 7.0.4)
      activejob (= 7.0.4)
      activerecord (= 7.0.4)
      activestorage (= 7.0.4)
      activesupport (= 7.0.4)
      mail (>= 2.7.1)
      net-imap
      net-pop
      net-smtp
    actionmailer (7.0.4)
      actionpack (= 7.0.4)
      actionview (= 7.0.4)
      activejob (= 7.0.4)
      activesupport (= 7.0.4)
      mail (~> 2.5, >= 2.5.4)
      net-imap
      net-pop
      net-smtp
      rails-dom-testing (~> 2.0)
    actionpack (7.0.4)
      actionview (= 7.0.4)
      activesupport (= 7.0.4)
      rack (~> 2.0, >= 2.2.0)
      rack-test (>= 0.6.3)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.2.0)
    actiontext (7.0.4)
      actionpack (= 7.0.4)
      activerecord (= 7.0.4)
      activestorage (= 7.0.4)
      activesupport (= 7.0.4)
      globalid (>= 0.6.0)
      nokogiri (>= 1.8.5)
    actionview (7.0.4)
      activesupport (= 7.0.4)
      builder (~> 3.1)
      erubi (~> 1.4)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.1, >= 1.2.0)
    activejob (7.0.4)
      activesupport (= 7.0.4)
      globalid (>= 0.3.6)
    activemodel (7.0.4)
      activesupport (= 7.0.4)
    activerecord (7.0.4)
      activemodel (= 7.0.4)
      activesupport (= 7.0.4)
    activestorage (7.0.4)
      actionpack (= 7.0.4)
      activejob (= 7.0.4)
      activerecord (= 7.0.4)
      activesupport (= 7.0.4)
      marcel (~> 1.0)
      mini_mime (>= 1.1.0)
    activesupport (7.0.4)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 1.6, < 2)
      minitest (>= 5.1)
      tzinfo (~> 2.0)
    builder (3.2.4)
    concurrent-ruby (1.1.10)
    crass (1.0.6)
    erubi (1.11.0)
    globalid (1.0.0)
      activesupport (>= 5.0)
    i18n (1.12.0)
      concurrent-ruby (~> 1.0)
    loofah (2.19.0)
      crass (~> 1.0.2)
      nokogiri (>= 1.5.9)
    mail (2.7.1)
      mini_mime (>= 0.1.1)
    marcel (1.0.2)
    method_source (1.0.0)
    mini_mime (1.1.2)
    minitest (5.16.3)
    net-imap (0.3.1)
      net-protocol
    net-pop (0.1.2)
      net-protocol
    net-protocol (0.1.3)
      timeout
    net-smtp (0.3.2)
      net-protocol
    nio4r (2.5.8)
    nokogiri (1.13.8-arm64-darwin)
      racc (~> 1.4)
    racc (1.6.0)
    rack (2.2.4)
    rack-test (2.0.2)
      rack (>= 1.3)
    rails (7.0.4)
      actioncable (= 7.0.4)
      actionmailbox (= 7.0.4)
      actionmailer (= 7.0.4)
      actionpack (= 7.0.4)
      actiontext (= 7.0.4)
      actionview (= 7.0.4)
      activejob (= 7.0.4)
      activemodel (= 7.0.4)
      activerecord (= 7.0.4)
      activestorage (= 7.0.4)
      activesupport (= 7.0.4)
      bundler (>= 1.15.0)
      railties (= 7.0.4)
    rails-dom-testing (2.0.3)
      activesupport (>= 4.2.0)
      nokogiri (>= 1.6)
    rails-html-sanitizer (1.4.3)
      loofah (~> 2.3)
    railties (7.0.4)
      actionpack (= 7.0.4)
      activesupport (= 7.0.4)
      method_source
      rake (>= 12.2)
      thor (~> 1.0)
      zeitwerk (~> 2.5)
    rake (13.0.6)
    thor (1.2.1)
    timeout (0.3.0)
    tzinfo (2.0.5)
      concurrent-ruby (~> 1.0)
    websocket-driver (0.7.5)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.5)
    zeitwerk (2.6.1)

PLATFORMS
  arm64-darwin-21

DEPENDENCIES
  actioncable (= 7.0.3)
  actionmailbox (= 7.0.3)
  actionmailer (= 7.0.3)
  actionpack (= 7.0.3)
  actiontext (= 7.0.3)
  actionview (= 7.0.3)
  activejob (= 7.0.3)
  activemodel (= 7.0.3)
  activerecord (= 7.0.3)
  activestorage (= 7.0.3)
  activesupport (= 7.0.3)
  builder (= 3.2.4)
  concurrent-ruby (= 1.1.10)
  crass (= 1.0.6)
  digest (= 3.1.0)
  erubi (= 1.10.0)
  globalid (= 1.0.0)
  i18n (= 1.10.0)
  loofah (= 2.17.0)
  mail (= 2.7.1)
  marcel (= 1.0.2)
  method_source (= 1.0.0)
  mini_mime (= 1.1.2)
  minitest (= 5.15.0)
  net-imap (= 0.2.3)
  net-pop (= 0.1.1)
  net-protocol (= 0.1.3)
  net-smtp (= 0.3.1)
  nio4r (= 2.5.8)
  nokogiri (= 1.13.6)
  racc (= 1.6.0)
  rack (= 2.2.3)
  rack-test (= 1.1.0)
  rails (= 7.0.3)
  rails-dom-testing (= 2.0.3)
  rails-html-sanitizer (= 1.4.2)
  railties (= 7.0.3)
  rake (= 13.0.6)
  strscan (= 3.0.3)
  thor (= 1.2.1)
  timeout (= 0.2.0)
  tzinfo (= 2.0.4)
  websocket-driver (= 0.7.5)
  websocket-extensions (= 0.1.5)
  zeitwerk (= 2.5.4)

BUNDLED WITH
   2.3.21
```

--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/rubygems/rubygems/search?q=undefined+method+%60metadata%27+for+nil+NilClass&type=Issues

If there aren't any reports for this error yet, please fill in the new issue form located at https://github.com/rubygems/rubygems/issues/new?labels=Bundler&template=bundler-related-issue.md, and copy and paste the report template above in there.
  ```
</details>

**Comment by flavorjones** [comment]
@Schwad You got further than I did on debugging this one. I'll try to set aside some time to dig in, but I don't think I know anything you don't know!

**Comment by camertron** [comment]
I looked into this and other issues recently, so I thought I'd link y'all to my PR: https://github.com/flavorjones/bundler-as_of/issues/9

**Comment by flavorjones** [comment]
Hey @camertron, thanks! For posterity the PR is at https://github.com/flavorjones/bundler-as_of/pull/10 and I'll schedule some time to take a look!

**Comment by camertron** [comment]
Hahaha woops, I totally linked to _this_ issue instead of my PR, thanks for adding the right link!
